// Auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          avatar_url: string | null;
          phone: string | null;
          role: string;
          company_id: string | null;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      companies: {
        Row: {
          id: string;
          name: string;
          gstin: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          phone: string | null;
          email: string | null;
          logo_url: string | null;
          owner_id: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['companies']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['companies']['Insert']>;
      };
      company_members: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          role: string;
          invited_by: string;
          joined_at: string;
        };
        Insert: Omit<Database['public']['Tables']['company_members']['Row'], 'joined_at'>;
        Update: Partial<Database['public']['Tables']['company_members']['Insert']>;
      };
      grn_templates: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          description: string | null;
          version: number;
          is_active: boolean;
          is_default: boolean;
          file_url: string | null;
          thumbnail_url: string | null;
          fields: Json;
          table_config: Json | null;
          page_count: number;
          created_by: string;
          ai_learning_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['grn_templates']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['grn_templates']['Insert']>;
      };
      extracted_invoices: {
        Row: {
          id: string;
          company_id: string;
          file_url: string;
          file_name: string;
          ocr_provider: string;
          extracted_data: Json;
          overall_confidence: number;
          processing_time_ms: number;
          created_by: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['extracted_invoices']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['extracted_invoices']['Insert']>;
      };
      grn_records: {
        Row: {
          id: string;
          company_id: string;
          template_id: string;
          invoice_id: string | null;
          grn_number: string;
          status: string;
          field_values: Json;
          line_items: Json;
          validation_errors: Json;
          is_validated: boolean;
          validation_score: number;
          invoice_file_url: string | null;
          grn_file_url: string | null;
          combined_pdf_url: string | null;
          ai_confidence: number;
          ai_notes: string | null;
          created_by: string;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
          approved_at: string | null;
          received_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['grn_records']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['grn_records']['Insert']>;
      };
      ai_training_data: {
        Row: {
          id: string;
          company_id: string;
          template_id: string;
          field_id: string;
          field_name: string;
          original_value: string;
          corrected_value: string;
          invoice_context: Json;
          vendor_name: string | null;
          created_by: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['ai_training_data']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['ai_training_data']['Insert']>;
      };
      activity_logs: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          action: string;
          entity_type: string;
          entity_id: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['activity_logs']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['activity_logs']['Insert']>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          read: boolean;
          link: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
